Blog app - views
khanh-devos/rail-blog-app pull request #6
Opened 2023-10-04 14:40 UTC by khanh-devos

- [x] Implement the design from the sneak peek wireframes.
- [x] Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)

2023-10-04 15:36 UTC, Lucas-Masaba requested changes
# Hello @khanh-devos  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Views are rendering on the browser :gear: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### [OPTIONAL]
- You have a bunch of commented code on your controllers and views that I cannot directly comment on in this review. I would suggest removing them if you are not using them.
- I also noticed that you do not have the photo field in your schema which should be there. I can't add photos when creating a user and so they do not appear in the UI.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 15:36 UTC, Lucas-Masaba commented on app/views/users/show.html.erb
>  <p style="color: green"><%= notice %></p>
- [x] You should use the `#recent_post` method you created in your model to render the user's 3 most recent posts.

2023-10-04 15:36 UTC, Lucas-Masaba commented on app/views/posts/index.html.erb
> +    <%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>
- [x] Use the `recent_comments` method you created in your Post model to render the 5 most recent comments here.

2023-10-05 09:20 UTC, khanh-devos commented
Thank you for your quick review, @Lucas-Masaba

2023-10-05 10:40 UTC, gemmen29 approved these changes
Hi @khanh-devos, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 11:03 UTC, merged